### ISSUE TITLE
"qemu-system-riscv64: rom check and register reset failed" error message.

### ISSUE THREAD

**Issue by clockzhong** [noteed/riscv-hello-c#1]
I build your prject successfully, but when running it, facing the following errors:

```
qemu-system-riscv64 -nographic -machine sifive_u -kernel build/bin/rv64imac/qemu-sifive_u/hello
rom: requested regions overlap (rom phdr #0: build/bin/rv64imac/qemu-sifive_u/hello. free=0x0000000080011488, addr=0x0000000080000000)
qemu-system-riscv64: rom check and register reset failed
```

Any suggest will be appreciated. Thanks!

And my qemu version is latest:
```
qemu-system-riscv64 -version
QEMU emulator version 5.2.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers

```

**Comment by noteed** [comment]
Hello, this seems to be the same problem reported and fixed here: https://github.com/noteed/riscv-hello-asm/issues/1. It also seems that this person had the same problem and fixed them too: https://github.com/bigmagic123/riscv-hello-c/commit/fb95abce32b180e33fe28463952784cf7f51b562

Can you report back if this information is enough for you ?

**Comment by clockzhong** [comment]
@noteed Thanks very much. I've successfully run your riscv-hello-asm in my env, it could work exactly as you described in your Readme. That is all what I need. But why this riscv-hello-c couldn't work in my env, I still don't know. I close this issue firstly
But I'll keep working on this issue, and will update it here if any finding. 
Thanks again. 
Clock

**Comment by noteed** [comment]
Good to hear. If you look at the issue I linked above, you should see some explanations (mostly, from what I remember, about QEMU changing some defaults). Thanks for the reply.
